name: Scheduled build

on:
  workflow_dispatch:

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      - name: world
        run: echo WORLD
      - name: cat
        run: cat .github/workflows/hello.yml
