name: Scheduled build

on:
  schedule:
    - cron: '15 9 * * 5'
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      - name: hello
        run: echo HELLO
      - name: cat
        run: cat .github/workflows/hello.yml
