name: Scheduled build

on:
  schedule:
    - cron: '58 6 * * 5'

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      - name: hello
        run: echo HELLO
      - name: cat
        run: cat .github/workflows/hello.yml
