name: Invoke build on world

on:
  schedule:
    - cron: '1 12 * * 5'

jobs:
  invoke:
    name: invoke
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh workflow run -R ohta/sandbox hello.yml --ref world
