name: Invoke build on world

on:
  schedule:
    - cron: '28 4 * * 5'

permissions:
  actions: write

jobs:
  invoke:
    name: invoke
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh workflow run -R ohta/sandbox hello.yml --ref world
